import {
  GiBroadsword,
  GiCrocSword,
  GiTwoHandedSword,
  GiRelicBlade,
  GiRuneSword,
  GiShatteredSword,
  GiSacrificialDagger,
  GiPocketBow,
  GiCrossedSwords,
  GiWizardStaff,
  GiNinjaArmor,
  GiChestArmor,
  GiHeartArmor,
  GiCapeArmor,
  GiLeatherArmor,
  GiShoulderArmor,
  GiRobe,
  GiRing,
  GiPowerRing,
  GiPoncho,
  GiEmeraldNecklace,
  GiPrimitiveNecklace,
  GiBracers,
  GiOldLantern,
  GiQuiver,
  GiFishingPole,
} from "react-icons/gi";

export const ITEM_ICONS = {
  //weapons
  GiBroadsword,
  GiCrocSword,
  GiTwoHandedSword,
  GiRelicBlade,
  GiRuneSword,
  GiShatteredSword,
  GiSacrificialDagger,
  GiPocketBow,
  GiCrossedSwords,
  GiWizardStaff,
  //armors
  GiNinjaArmor,
  GiChestArmor,
  GiHeartArmor,
  GiCapeArmor,
  GiLeatherArmor,
  GiShoulderArmor,
  GiRobe,
  // accessories
  GiRing,
  GiPowerRing,
  GiPoncho,
  GiEmeraldNecklace,
  GiPrimitiveNecklace,
  GiBracers,
  GiOldLantern,
  GiQuiver,
  GiFishingPole,
} as const;

export type ItemIconName = keyof typeof ITEM_ICONS;
