import type { Quest } from "./quests.types";

export const DEFAULT_QUESTS: Quest[] = [
  {
    id: 1,
    title: "Cantinho organizado",
    description: "Arrume sua cama, mesa ou o que mais precisar.",
    status: "open",
    points: 20,
    category: "Casa",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 2,
    title: "Leitura diária",
    description: "Ler algumas páginas de um livro.",
    status: "open",
    points: 20,
    category: "Outro",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 3,
    title: "Aprendizado",
    description: "Estude algum tópico que seja do seu interesse.",
    status: "open",
    points: 20,
    category: "Estudo",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 4,
    title: "Preparar a comida",
    description: "Fazer e guardar a comida da semana",
    status: "open",
    points: 80,
    category: "Casa",
    createdAt: new Date(),
    completedAt: null,
    type: "weekly",
  },
  {
    id: 5,
    title: "Lavar roupas",
    description: "Lavar, secar e guardar as roupas",
    status: "open",
    points: 80,
    category: "Casa",
    createdAt: new Date(),
    completedAt: null,
    type: "weekly",
  },
  {
    id: 6,
    title: "Planejamento",
    description: "Organize seu cronograma do dia.",
    status: "open",
    points: 20,
    category: "Outro",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 7,
    title: "Melhor amigo do homem",
    description: "Levar o seu cachorro para passear na rua.",
    status: "open",
    points: 20,
    category: "Casa",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 8,
    title: "Trabalho focado",
    description: "Entregar o resultado esperado do dia no trabalho.",
    status: "open",
    points: 20,
    category: "Trabalho",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 9,
    title: "Academia",
    description: "Ir à academia uma vez por dia",
    status: "open",
    points: 20,
    category: "Saúde",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 10,
    title: "Casa em ordem",
    description: "Limpar a casa, ou parte dela.",
    status: "open",
    points: 80,
    category: "Casa",
    createdAt: new Date(),
    completedAt: null,
    type: "weekly",
  },
  {
    id: 11,
    title: "Revisão semanal",
    description: "Revisar a semana que passou e oganizar a próxima",
    status: "open",
    points: 80,
    category: "Outro",
    createdAt: new Date(),
    completedAt: null,
    type: "weekly",
  },
  {
    id: 12,
    title: "Conexão social",
    description: "Se conecte com quem você se importa de algum jeito.",
    status: "open",
    points: 20,
    category: "Outro",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
  {
    id: 13,
    title: "Praticar um esporte",
    description: "Tire um dia na semana para praticar algum esporte.",
    status: "open",
    points: 80,
    category: "Saúde",
    createdAt: new Date(),
    completedAt: null,
    type: "weekly",
  },
  {
    id: 14,
    title: "Bem dormido, bem dormido",
    description: "Tenha pelo menos 7h de sono por dia.",
    status: "open",
    points: 20,
    category: "Saúde",
    createdAt: new Date(),
    completedAt: null,
    type: "daily",
  },
];
